name: Deploy Django App

on:
  push:
    branches:
      - mainnnn

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Transfer codebase to Droplet
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -av --delete  --exclude='venv'
          path: './'
          remote_path: '/home/ubuntu/appraise-django-app'
          remote_host: ${{ secrets.SERVER_IP }}
          remote_user: ${{ secrets.SERVER_USER }}
          remote_key: ${{ secrets.SERVER_KEY }}

      - name: Restart Gunicorn service
        id: restart_gunicorn
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/appraise-django-app/
            /home/ubuntu/appraise-django-app/venv/bin/pip install -q -r requirements.txt
            sudo systemctl restart gunicorn
            touch ~/CICD_did_this